---
- name : create new instance
  ec2:
    key_name: ansibletower
    instance_type: t2.micro
    image: ami-0f9cf087c1f27d9b1
    region: us-east-1
    wait: yes
    group: launch-wizard-23
    count: 1
    vpc_subnet_id: subnet-1272d74e
    assign_public_ip: no
