---
- name: create Autoscaling Groups
  ec2_asg:
    name: special
    load_balancers: "{{ elbname }}"
    region: us-east-1
    availability_zones: [ 'us-east-1e', 'us-east-1c' ]
    launch_config_name: ansibletower-08Jan2019-1327
    min_size: 1
    max_size: 1
    desired_capacity: 1
    vpc_zone_identifier: [ 'subnet-6a09ac0d', 'subnet-81ac46bf' ]
    tags:
      - environment: production
        propagate_at_launch: no
  #ec2_asg:
    #name: asgdemo
    #load_balancers: "{{ elbname }}"
    #instance_ids: i-01621eb958bde16f0
    #region: us-east-1
    #availability_zones: ['us-east-1e', 'us-east-1c']
    ##availability_zones:
      #- "{{ zonea }}"
      #- "{{ zoneb }}"
    #launch_config_name: ansibletower-08Jan2019-1327
    #min_size: 1
    #max_size: 1
    #desired_capacity: 1
    #vpc_zone_identifier: ['subnet-6a09ac0d', 'subnet-81ac46bf']
    #vpc_zone_identifier:
      #- "{{ subneta }}"
      #- "{{ subnetb}}"
    #tags:
      #- environment: production
        #propagate_at_launch: no
